services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: wpengine/site-deploy:latest
    platform: linux/amd64
    entrypoint: /tests/test-make-relative-remote/test.sh
    volumes:
      - ./tests/workspace:/workspace
    depends_on:
      - build

  build:
    image: wpengine/site-deploy:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: /bin/true
