  <?php
  /**
   * Plugin Name: Custom Plugin Object Cache Fixture
   * Plugin URI: https://github.com/wpengine/site-deploy
   * Version: 0.0.1
   */

   /**
    * This cache plugin is used to test the dynamic, absolute pathing generated by exclude-from.sh.
    *
    * The file should be included, even though /cache/* and /object-cache.php are both sometimes
    * excluded by the exclude-from.sh script.
    */

   add_action('init', 'register_my_cpt');

   function register_my_cpt() {
      register_post_type('my-cpt', array(
          'public' => true
      ));
   }